CREATE TABLE IF NOT EXISTS parametros_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chave VARCHAR(100) NOT NULL UNIQUE,
  valor_numeric DECIMAL(19,2) NULL,
  valor_texto   VARCHAR(255) NULL
);

-- default de custo/km
MERGE INTO parametros_config (chave, valor_numeric) KEY (chave)
VALUES ('CUSTO_KM', 1.50);
